apiVersion: v1
kind: ConfigMap
metadata:
  name: floci-log-analyzer-config
data:
  S3_BUCKET: "SKM-Bucket"
  S3_KEY: "apache_logs"
  S3_ENDPOINT_URL: "http://host.docker.internal:4566"
  AWS_DEFAULT_REGION: "us-east-1"
