apiVersion: apps/v1
kind: Deployment
metadata:
  name: floci-log-analyzer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: floci-log-analyzer
  template:
    metadata:
      labels:
        app: floci-log-analyzer
    spec:
      containers:
        - name: floci-log-analyzer
          image: host.docker.internal:5100/floci-eks-log-analyzer:v2
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: floci-log-analyzer-config
            - secretRef:
                name: floci-log-analyzer-secret
